import type { PathfinderSyncSource } from './types';

/**
 * 自动同步只允许访问这份代码内白名单。数据库只保存同步状态，不能覆盖 fetchUrl，
 * 避免后台误配置或公开输入把服务端变成任意 URL 代理。
 */
export const PATHFINDER_SYNC_SOURCES: readonly PathfinderSyncSource[] = [
  {
    id: 'openai-news',
    name: 'OpenAI News',
    adapterId: 'rss',
    fetchUrl: 'https://openai.com/news/rss.xml',
    siteUrl: 'https://openai.com/news/',
    allowedFetchHosts: ['openai.com'],
    allowedItemHosts: ['openai.com'],
    itemType: 'ai-update',
    direction: 'ai',
    trustLevel: 'official',
    enabled: true,
    autoPublish: true,
    organization: 'OpenAI',
    learningEligible: false,
  },
  {
    id: 'hugging-face-blog',
    name: 'Hugging Face Blog',
    adapterId: 'rss',
    fetchUrl: 'https://huggingface.co/blog/feed.xml',
    siteUrl: 'https://huggingface.co/blog',
    allowedFetchHosts: ['huggingface.co'],
    allowedItemHosts: ['huggingface.co'],
    itemType: 'ai-update',
    direction: 'ai',
    trustLevel: 'verified',
    enabled: true,
    autoPublish: false,
    organization: 'Hugging Face',
    learningEligible: false,
  },
  {
    id: 'google-deepmind-blog',
    name: 'Google DeepMind Blog',
    adapterId: 'rss',
    fetchUrl: 'https://deepmind.google/blog/rss.xml',
    siteUrl: 'https://deepmind.google/blog/',
    allowedFetchHosts: ['deepmind.google'],
    allowedItemHosts: ['deepmind.google'],
    itemType: 'ai-update',
    direction: 'ai',
    trustLevel: 'official',
    enabled: true,
    autoPublish: true,
    organization: 'Google DeepMind',
    learningEligible: false,
  },
  {
    id: 'google-ai-blog',
    name: 'Google AI',
    adapterId: 'rss',
    fetchUrl: 'https://blog.google/technology/ai/rss/',
    siteUrl: 'https://blog.google/technology/ai/',
    allowedFetchHosts: ['blog.google'],
    allowedItemHosts: ['blog.google'],
    itemType: 'ai-update',
    direction: 'ai',
    trustLevel: 'official',
    enabled: true,
    autoPublish: true,
    organization: 'Google',
    learningEligible: false,
  },
  {
    id: 'github-ai-blog',
    name: 'GitHub AI & ML',
    adapterId: 'rss',
    fetchUrl: 'https://github.blog/ai-and-ml/feed/',
    siteUrl: 'https://github.blog/ai-and-ml/',
    allowedFetchHosts: ['github.blog'],
    allowedItemHosts: ['github.blog'],
    itemType: 'ai-update',
    direction: 'ai',
    trustLevel: 'official',
    enabled: true,
    autoPublish: true,
    organization: 'GitHub',
    learningEligible: false,
  },
  {
    id: 'github-good-first-issues',
    name: 'GitHub Good First Issues',
    adapterId: 'github',
    fetchUrl: 'https://api.github.com/search/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22+no%3Aassignee+archived%3Afalse&sort=updated&order=desc&per_page=30',
    siteUrl: 'https://github.com/topics/good-first-issue',
    allowedFetchHosts: ['api.github.com'],
    allowedItemHosts: ['github.com'],
    itemType: 'open-source',
    direction: 'ai',
    trustLevel: 'verified',
    enabled: true,
    autoPublish: false,
    organization: 'GitHub',
    learningEligible: true,
  },
] as const;

export const PATHFINDER_SYNC_SOURCE_MAP = new Map(
  PATHFINDER_SYNC_SOURCES.map((source) => [source.id, source]),
);
